spring:
  datasource:
    url: jdbc:mysql://192.168.20.166/my_db?${db-settings}
    username: root
    password: 123456

  security:
    user:
      name: admin
      password: 123456
logging:
  pattern:
    console: '%clr(%d{${LOG_DATEFORMAT_PATTERN:yy-MM-dd HH:mm:ss.SSS}}){faint} %clr(${LOG_LEVEL_PATTERN:%5p}) %clr(|){faint} %clr([%t]){faint} %clr(%logger{45}[%line]:){cyan} %m%n${LOG_EXCEPTION_CONVERSION_WORD:%wEx}'

#mybatis-plus:
#  configuration:
#    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
